# Generated by Django 4.1 on 2023-04-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
